

#ifndef GPP_NETCODES_H
#define GPP_NETCODES_H

enum GPP_NET_EVENT_TYPES{
    GNET_NONE = 0,
    GNET_CONNECTED,
    GNET_DISCONNECTED,
    GNET_DATA,
    GNET_LOG
};

enum GPP_NET_ACTIVE_STATS{
    GNT_DEFAULT = 0,
    GNT_SETUP,
    GNT_RUNNING,
    GNT_STOPPING,
    GNT_STOPPED
};

enum GPP_NET_PEER_STATS{
GNET_PEER_DEFAULT=0,
GNET_PEER_CONNECTED=1,
GNET_PEER_DISCONNECTING=2,
GNET_PEER_DISCONNECTED=3
};
#endif
