// -*- C++ -*-
//
// generated by wxGlade 1.1.0pre on Mon Aug  7 15:19:21 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef AMBIENTEEDITORDIALOG_H
#define AMBIENTEEDITORDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>

#include <wx/listctrl.h>
#include <wx/notebook.h>



class AmbienteEditorDialog: public wxDialog {
public:
 AmbienteEditorDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
 // begin wxGlade: AmbienteEditorDialog::attributes
 wxNotebook* nt1;
 wxPanel* notebook_1_pane_1;
 wxTextCtrl* txt_name;
 wxTextCtrl* txt_timestep;
 wxTextCtrl* txt_min;
 wxTextCtrl* txt_max;
 wxCheckBox* checkbox_1;
 wxTextCtrl* txt_gravity;
 wxPanel* notebook_1_pane_2;
 wxListCtrl* lb_objects;
 wxButton* btn_add;
 wxButton* btn_edit;
 wxButton* btn_remove;
 wxButton* button_OK;
 wxButton* button_CANCEL;
 // end wxGlade

 DECLARE_EVENT_TABLE();

public:
 virtual void checkButtonCallback(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // AMBIENTEEDITORDIALOG_H
