// -*- C++ -*-
//
// generated by wxGlade 1.1.0pre on Mon Aug  7 13:56:26 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PROTOFRAME_H
#define PROTOFRAME_H

#include <wx/wx.h>
#include <wx/image.h>




class ProtoFrame: public wxFrame {
public:
 ProtoFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
 // begin wxGlade: ProtoFrame::attributes
 wxMenuBar* ProtoMenu;
 wxPanel* panel_1;
 // end wxGlade

 DECLARE_EVENT_TABLE();

public:
 virtual void checkMenuCallback(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PROTOFRAME_H
